### ISSUE TITLE
Could not resolve com.github.LinXunFeng:flutter_chat_bottom_container_aar:0.0.1.

### ISSUE THREAD

**Issue by xiao666Git** [LinXunFeng/flutter_chat_packages#1]
> Could not resolve com.github.LinXunFeng:flutter_chat_bottom_container_aar:0.0.1.
         > Could not get resource 'https://repo.maven.apache.org/maven2/com/github/LinXunFeng/flutter_chat_bottom_container_aar/0.0.1/flutter_chat_bottom_container_aar-0.0.1.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/com/github/LinXunFeng/flutter_chat_bottom_container_aar/0.0.1/flutter_chat_bottom_container_aar-0.0.1.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.6.3/userguide/build_environment.html#gradle_system_properties
                  > Remote host terminated the handshake

**Comment by LinXunFeng** [comment]
`README` 好好看

**Comment by xiao666Git** [comment]
哦哦  解决

allprojects {
  repositories {
    ...
    maven { url 'https://jitpack.io' }
  }
}

插件很好用，感谢作者
