### ISSUE TITLE
我开始直接点输入框，上面的列表内容 没有顶起来，我希望能够顶起来，这要如何做呐？

### ISSUE THREAD

**Issue by liuquanyu** [LinXunFeng/flutter_chat_packages#12]
### Description

https://github.com/user-attachments/assets/94f2d06b-5f47-45a6-9ba5-0f4005b59ffa

**Comment by LinXunFeng** [comment]
请附上系统，版本号（系统、库），`flutter doctor` 这些信息

**Comment by LinXunFeng** [comment]
iOS 的版本号是多少？

**Comment by LinXunFeng** [comment]
你这是直接跑的这个库的 `Demo` 还是你自己依赖该库创建的 `Demo`？如果是自己创建的，请先尝试当前库的 `Demo` 是否有这个问题

**Comment by liuquanyu** [comment]
我是直接把代码 拷贝过来，在我项目上跑的，我项目： sdk: ">=3.3.4 <4.0.0"，引入的chat_bottom_container: ^0.2.0，
![image](https://github.com/user-attachments/assets/50e4729b-2355-4e35-9543-f04b53322ac3)

**Comment by LinXunFeng** [comment]
先跑一下当前库的 `Demo`，好排查问题！

你截图里的是更新的内容，iOS 的版本号需要你在关于本机里看

**Comment by liuquanyu** [comment]
嗯嗯，我手机版本是。 17.6.1 的

**Comment by liuquanyu** [comment]
demo 没问题，那是跟我的项目 有冲突吗，我看区别，就 App.routeObserver 这个吧，我项目是用的getx，  navigatorObservers: [
              RoutePages.observer,
            ],

**Comment by liuquanyu** [comment]
奇了怪了，代码没啥区别啊，怎么就顶不起来呐

**Comment by LinXunFeng** [comment]
附上你的可复现 `demo`，我得跑跑看才能知道问题

**Comment by shywoody** [comment]
> 附上你的可复现 `demo`，我得跑跑看才能知道问题

1. 跑demo没问题,  基本照着demo写的, 有几点异同
    1) 没有对input进行demo更新
```
bool updateInputView({
    required bool isReadOnly,
  }) {
    if (readOnly != isReadOnly) {
      readOnly = isReadOnly;
      // You can just refresh the input view.
      setState(() {});
      return true;
    }
    return false;
  }
```
    2)没有进行changeKeyboardPanelHeight: widget.changeKeyboardPanelHeight设置,因为有些高度是自适应的没有具体高度
```
如下的代码是没有的没有将高度回调出去
  Widget _buildEmojiPickerPanel() {
    // If the keyboard height has been recorded, priority is given to setting
    // the height to the keyboard height.
    double height = 300;
    final keyboardHeight = controller.keyboardHeight;
    if (keyboardHeight != 0) {
      if (widget.changeKeyboardPanelHeight != null) {
        height = widget.changeKeyboardPanelHeight!.call(keyboardHeight);
      } else {
        height = keyboardHeight;
      }
    }

    return Container(
      padding: EdgeInsets.zero,
      height: height,
      color: Colors.blue[50],
      child: const Center(
        child: Text('Emoji Panel'),
      ),
    );
  }
```
    3) TextFiled也没有设置readOnly: readOnly, 没有监听点击设置keyboard
    4) 没有设置safearea高度,利用您插件自带生成
2.视频如下

https://github.com/user-attachments/assets/8e93cd1e-b97a-4d27-aff9-b0859d0576ef
红色container是定高, 其他不是定高不知道是什么问题导致有点回弹效果,运行demo就挺好

**Comment by LinXunFeng** [comment]
@shywoody 你这个跟当前 `issue` 下不是同个问题，建议你重新开个 `issue` 来说，不要打扰到他人

看你的效果，大概率是加号对应的这个视图是有使用 `MediaQuery.paddingOf(context).bottom` 或其它安全区的东西

**Comment by LinXunFeng** [comment]
相关 `issue`: https://github.com/OpenFlutter/flutter_screenutil/issues/385
