### ISSUE TITLE
[Bug report] IOS打完包核对包时候报错

### ISSUE THREAD

**Issue by java8site** [LinXunFeng/flutter_chat_packages#13]
### Steps to reproduce

Upload Symbols Failed
The archive did not include a dSYM for the FSAChatBottomContainer.framework with the UUIDs [576CF4E9-2C57-339C-859C-6FA8C03F2196]. Ensure that the archive's dSYM folder includes a DWARF file for FSAChatBottomContainer.framework with the expected UUIDs.

### Expected results

FSAChatBottomContainer正常不应该不错呀

### Actual results

Upload Symbols Failed
The archive did not include a dSYM for the FSAChatBottomContainer.framework with the UUIDs [576CF4E9-2C57-339C-859C-6FA8C03F2196]. Ensure that the archive's dSYM folder includes a DWARF file for FSAChatBottomContainer.framework with the expected UUIDs.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
FSAChatBottomContainer

</details>

**Comment by LinXunFeng** [comment]
我这边没遇到这个问题，一切正常。

## 需要你提供以下信息
- 你用的什么工具进行的打包？
- 上传符号表用的是什么？

## 需要你做的检查
- 查看是否正常选择 `DWARF with dSYM File`

<img width="1018" alt="image" src="https://github.com/user-attachments/assets/7aff800d-e1d4-4224-a6bf-a879971fa1d1">

如果跟截图中的一致，你可以尝试把 `Debug` 项也选择 `DWARF with dSYM File` 再打包

**Comment by java8site** [comment]
> 我这边没遇到这个问题，一切正常。
> 
> ## 需要你提供以下信息
> * 你用的什么工具进行的打包？
> * 上传符号表用的是什么？
> 
> ## 需要你做的检查
> * 查看是否正常选择 `DWARF with dSYM File`
> 
> <img alt="image" width="1018" src="https://private-user-images.githubusercontent.com/19367531/376086753-7aff800d-e1d4-4224-a6bf-a879971fa1d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NzM1NjMsIm5iZiI6MTcyODg3MzI2MywicGF0aCI6Ii8xOTM2NzUzMS8zNzYwODY3NTMtN2FmZjgwMGQtZTFkNC00MjI0LWE2YmYtYTg3OTk3MWZhMWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDAyMzQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMTU0OTZkZGIyNmU3MGNiZTRlZmVmODBlODI1YzcwZDNjNjVkMGFjMzViZDM4MWJhYWU1MjNjOGU0NTM2MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._YkdXEZF2QAyhzPMfmgANP90ssloKMIHhUD0LoNmx-s">
> 如果跟截图中的一致，你可以尝试把 `Debug` 项也选择 `DWARF with dSYM File` 再打包

我是使用xcode打包, 已经按照上面你发的图debug项目也选择了DWARF with dsym file, 还是出现同样的错误.
xcode版本是: Xcode 16.0
mac版本是: 15.0.1 (24A348)
[](url)

**Comment by java8site** [comment]
![1728876584930](https://github.com/user-attachments/assets/a2d0b177-839a-4e49-9a74-09bb94dd9b03)
@LinXunFeng

**Comment by java8site** [comment]
![1728876848172](https://github.com/user-attachments/assets/c118a24b-4c15-4d19-ac59-8afad628d03f)
@LinXunFeng

**Comment by java8site** [comment]
上传符号表用的是什么？, 这个怎么看? 不好意思哈, 我是新手 @LinXunFeng

**Comment by LinXunFeng** [comment]
按如下步骤操作，看看是否有对应的 `chat_bottom_container.framework.dSYM`

<img width="530" alt="image" src="https://github.com/user-attachments/assets/576329a5-5dfd-42c4-8748-70cb5ae70ea2">

<img width="452" alt="image" src="https://github.com/user-attachments/assets/51f7bc7f-7a36-4975-ab73-66116fc2164d">

<img width="568" alt="image" src="https://github.com/user-attachments/assets/a4e62f2d-4bb2-4338-9c1d-d2f04d1aee6f">

**Comment by java8site** [comment]
> 按如下步骤操作，看看是否有对应的 `chat_bottom_container.framework.dSYM`
> 
> <img alt="image" width="530" src="https://private-user-images.githubusercontent.com/19367531/376104160-576329a5-5dfd-42c4-8748-70cb5ae70ea2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4Nzg5MTYsIm5iZiI6MTcyODg3ODYxNiwicGF0aCI6Ii8xOTM2NzUzMS8zNzYxMDQxNjAtNTc2MzI5YTUtNWRmZC00MmM0LTg3NDgtNzBjYjVhZTcwZWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDA0MDMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYjZkYjFlZjdiYzhlNjEzYmNiYTRjY2YzZmYzZDVmM2IyNmNjMmRmNDMxZDZkYmEwZjQzYWE2MGMzZTBhMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ysoubkP1Wnyir6Sq8DcVXJsBTP3WqqCAxbZJ_Ij1gDw"> <img alt="image" width="452" src="https://private-user-images.githubusercontent.com/19367531/376104193-51f7bc7f-7a36-4975-ab73-66116fc2164d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4Nzg5MTYsIm5iZiI6MTcyODg3ODYxNiwicGF0aCI6Ii8xOTM2NzUzMS8zNzYxMDQxOTMtNTFmN2JjN2YtN2EzNi00OTc1LWFiNzMtNjYxMTZmYzIxNjRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDA0MDMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkOWY2YjE3NzQxODNhZDU0MjY2YTlkNWZlOGY2ODE1MzI2NDJjYTZhNDEyZTU3NmUzMGUyNTgxMWYyM2NmZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EDcR7-s7Jr3fpr6Cq3vQ5Rs-dmgfrI1P1wv115lGrsI"> <img alt="image" width="568" src="https://private-user-images.githubusercontent.com/19367531/376104237-a4e62f2d-4bb2-4338-9c1d-d2f04d1aee6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4Nzg5MTYsIm5iZiI6MTcyODg3ODYxNiwicGF0aCI6Ii8xOTM2NzUzMS8zNzYxMDQyMzctYTRlNjJmMmQtNGJiMi00MzM4LTljMWQtZDJmMDRkMWFlZTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDA0MDMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzM2EzM2Y1ZTA4ZWU3ODBkZmZkZDliNzc5YzJjNTc4ZjRiZDFmZDVlMWM1ZTA4NjJlYzFhNDkwNjEwZmVhNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YBeCVmyxbX300wEkTpLRCffoWOoYHOmiqUuF1dzB5V4">

有chat_bottom_container.framework.dSYM

**Comment by LinXunFeng** [comment]
- 现在的 `MacOS` 版本和 `Xcode` 版本是多少？
- 项目可以正常运行吗？
- 项目中 `chat_bottom_container` 的功能是否正常？

**Comment by java8site** [comment]
> * 现在的 `MacOS` 版本和 `Xcode` 版本是多少？
> * 项目可以正常运行吗？
> * 项目中 `chat_bottom_container` 的功能是否正常？

版本:
xcode版本是: Xcode 16.0
mac版本是: 15.0.1 (24A348)
app还没上架, 本地测试功能都正常
项目中chat_bottom_comtainer使用都正常
现在准备上架, 然后才报这个错误

**Comment by java8site** [comment]
The archive did not include a dSYM for the FSAChatBottomContainer.framework with the UUIDs [576CF4E9-2C57-339C-859C-6FA8C03F2196]. Ensure that the archive's dSYM folder includes a DWARF file for FSAChatBottomContainer.framework with the expected UUIDs.

这是不是UUIDS不一致,或者不包含导致的? 可以排查这个UUIDS吗? @LinXunFeng

**Comment by java8site** [comment]
![1728884151701](https://github.com/user-attachments/assets/f05e5f65-ed5c-4f7c-a6d2-9458d5fe3ec4)
我使用dwarfdump --uuid 来获取chat_bottom_container.framework.dSYM的UUIDS和 报错提示的UUIDs [576CF4E9-2C57-339C-859C-6FA8C03F2196]不一致

**Comment by LinXunFeng** [comment]
查看 `UUIDs` 可以用下方命令

```shell
dwarfdump --uuid chat_bottom_container.framework.dSYM的路径
```

不过我觉得更可能的是因为 `MacOS 15` + `Xcode 16.0` 这个组合

<img width="1105" alt="image" src="https://github.com/user-attachments/assets/b9008a05-6a16-42ac-b68e-eafd497bb3ea">

资料
- [Upload Symbols Failed on Xcode 16](https://forums.developer.apple.com/forums/thread/763731?answerId=803773022#803773022)
- https://stackoverflow.com/a/79007927/8577739

**Comment by java8site** [comment]
> * Upload Symbols Failed on Xcode 16

👌, 那我先试试忽略这个报警, 然后上架看看有什么问题没

**Comment by java8site** [comment]
这个报错预警尝试了很多方法, 还是一直存在. 但是不影响正常上架. 感谢作者大佬
