### ISSUE TITLE
保持聊天内容触底

### ISSUE THREAD

**Issue by Pony666-max** [LinXunFeng/flutter_chat_packages#14]
### Use case

能不能实现和微信一样，打开面板或者弹出键盘时保持聊天内容触底啊，作者大大辛苦啦

### Proposal

能不能实现和微信一样，打开面板或者弹出键盘时保持聊天内容触底啊，作者大大辛苦啦

**Comment by LinXunFeng** [comment]
在 `onPanelTypeChange` 里调用 `scrollController.jumpTo(0)` 不可以吗？

**Comment by Pony666-max** [comment]
不行呢，因为呼起键盘有过渡时间，但是onPanelTypeChange只呼起前触发一次

**Comment by LinXunFeng** [comment]
你们的列表不是倒序的吗？

**Comment by Pony666-max** [comment]
改为倒序可以了，感谢哈
