### ISSUE TITLE
0.2.1版本导致安卓导航栏不沉浸，变黑了好丑

### ISSUE THREAD

**Issue by Pony666-max** [LinXunFeng/flutter_chat_packages#15]
### Steps to reproduce

0.2.1版本导致安卓导航栏不沉浸，变黑了好丑

### Expected results

0.2.1版本导致安卓导航栏不沉浸，变黑了好丑

### Actual results

0.2.1版本导致安卓导航栏不沉浸，变黑了好丑

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by Pony666-max** [comment]
可以修复一下嘛大佬，有偿

**Comment by LinXunFeng** [comment]
你在 issue 的描述里上传一下该库引入前后的对比截图，我们现在不知道你说的是什么现象。

然后提供一下最小可复现 demo，方便我们定位问题

**Comment by Pony666-max** [comment]
<img width="409" alt="iShot_2
<img width="495" alt="iShot_2024-11-18_22 17 44" src="https://github.com/user-attachments/assets/d8d47684-e8aa-41e7-afb8-0b5ca457f4b1">
<img width="498" alt="iShot_2024-11-18_22 17 56" src="https://github.com/user-attachments/assets/ef7b5ddd-03a9-464d-aa9b-7875ea250f5c">
024-11-18_22 15 42" src="https://github.com/user-attachments/assets/641e56ff-a80e-494f-8723-365362eca6d3">
<img width="409" alt="iShot_2024-11-18_22 17 37" src="https://github.com/user-attachments/assets/2cf4aa02-7b22-4693-95fe-946e141979b1">
我换成0.2.0运行就正常，改成最新版^0.2.1重新编译运行就有黑底了，不沉浸了获取不到底部安全距离了，你看辛苦一下排查有没有用到原生window.isNavigationBarContrastEnforced之类的函数，我这测试安卓10-15版本都有这个问题

**Comment by Pony666-max** [comment]
![Uploading iShot_2024-11-18_22.15.42.png…]()

**Comment by Pony666-max** [comment]
<img width="409" alt="iShot_2024-11-18_22 15 42" src="https://github.com/user-attachments/assets/b1a06358-4b9f-4d62-a026-045f6a6062a2">

**Comment by LinXunFeng** [comment]
你先试一下不引入该库，看看原本项目是不是非沉浸式的

**Comment by Pony666-max** [comment]
这样测我得删很多东西呢，很麻烦哦，但是我敢确定以前是沉浸的，这个项目写了半年多了，刚开始用你的0.2.0版本也正常，好像上个月升级了你这个版本才不行的

**Comment by Pony666-max** [comment]
我现在退回0.2.0版本正常了，还是希望你能在最新版修复这个问题，毕竟0.2.1优化了一些键盘高度计算之类的稳定多了

**Comment by Pony666-max** [comment]
我现在回退了问题解决了呀，底部安全距离可以用MediaQuery.of(context).padding.bottom获取，咋们可以加个v嘛大佬，CF_130 这我v

**Comment by LinXunFeng** [comment]
改回 `0.2.1`，然后按如下设置
```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setEnabledSystemUIMode(
    SystemUiMode.manual,
    overlays: [
      SystemUiOverlay.top,
    ],
  );
  runApp(const MyApp());
}
```

|Before|After|
|-|-|
|<img width="478" alt="image" src="https://github.com/user-attachments/assets/4b0add44-a996-4b55-9078-28a697d7fc50">|<img width="478" alt="image" src="https://github.com/user-attachments/assets/aa96c2fa-f68f-4b5e-bb7a-7d36d8902a8d">|
