### ISSUE TITLE
[Feature request] otherPanelWidget 能把safeAreaBottom 高度传递出来

### ISSUE THREAD

**Issue by huangpj0210** [LinXunFeng/flutter_chat_packages#16]
### Use case

在_buildOtherPanel使用SafeArea保留底部安全距离会出现出现弹跳的情况，如果使用ChatBottomPanelContainer otherPanelWidget 回调传递safeAreaBottom加 bottom padding会明显改善
使用 SafeArea 组件效果
https://github.com/user-attachments/assets/c8b442e8-71d9-4c95-a1bf-1cd6e83dbd66
```dart
 return SafeArea(
      child: SizedBox(height: 320, child: Placeholder()),
    );
```
使用组件_buildOtherPanel回调safeAreaBottom的效果
https://github.com/user-attachments/assets/05938d4f-0565-4a8e-9612-61343b95548f
```dart
return Container(
        height: 320,
        padding: EdgeInsets.only(bottom: widget.safeAreaBottom),
        child: Placeholder());
```

### Proposal

希望在_buildOtherPanel 的otherPanelWidget 把safeAreaBottom 传递出来
![image](https://github.com/user-attachments/assets/af656316-786a-4da7-ba38-857994951f32)

**Comment by LinXunFeng** [comment]
传递出去的改动会让所有人在升级后都得调整，我觉得不是很必要。

其实这个很好处理，你在进入页面后将底部安全高度记录起来，后面需要的时候拿来用就好了。

```dart
import 'package:flutter_screenutil/flutter_screenutil.dart';

class State {
  double bottomSafeHeight = ScreenUtil().bottomBarHeight;
}
```

```dart
return Container(
    height: 320,
    padding: EdgeInsets.only(bottom: state.bottomSafeHeight),
    child: Placeholder(),
);
```

**Comment by huangpj0210** [comment]
> 传递出去的改动会让所有人在升级后都得调整，我觉得不是很必要。
> 
> 其实这个很好处理，你在进入页面后将底部安全高度记录起来，后面需要的时候拿来用就好了。
> 
> ```dart
> import 'package:flutter_screenutil/flutter_screenutil.dart';
> 
> class State {
>   double bottomSafeHeight = ScreenUtil().bottomBarHeight;
> }
> ```
> 
> ```dart
> return Container(
>   height: 320,
>   padding: EdgeInsets.only(bottom: state.bottomSafeHeight),
>   child: Placeholder(),
> );
> ```

目前我也是采取类似的方案，ChatBottomPanelContainerController能获取safeAreaBottom的方案就不需要调整代码，类似于keyboardHeight的值获取
![image](https://github.com/user-attachments/assets/2d9afe67-a9d4-481b-b1be-dd1afc3a5303)

**Comment by LinXunFeng** [comment]
已在 `0.3.0` 版本中给 `ChatBottomPanelContainerController` 添加 `safeAreaBottom`
