### ISSUE TITLE
Performance! Help me.

### ISSUE THREAD

**Issue by Danilz-2706** [LinXunFeng/flutter_chat_packages#3]
If I open the keyboard first, all performance goes well.
However, if I open other panels first, there is a certain delay.
(I use according to readme/example)

Video 1: Open the keyboard first.

https://github.com/user-attachments/assets/1a92ca7e-de2c-4bb0-bd23-29ae77f08c2d

Video 2: Other panels are opened.

https://github.com/user-attachments/assets/444bc91b-aee0-4327-a34e-675a716a7915

**Comment by Danilz-2706** [comment]
<img width="428" alt="Screenshot 2024-07-24 at 4 33 53 PM" src="https://github.com/user-attachments/assets/3726f3a6-2b60-4e7d-bb1b-b137a7537e70">

When I have the keyboard size attached, it still doesn't work

**Comment by LinXunFeng** [comment]
> <img alt="Screenshot 2024-07-24 at 4 33 53 PM" width="428" src="https://private-user-images.githubusercontent.com/79782235/351660592-3726f3a6-2b60-4e7d-bb1b-b137a7537e70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MzA3MjYsIm5iZiI6MTcyMTgzMDQyNiwicGF0aCI6Ii83OTc4MjIzNS8zNTE2NjA1OTItMzcyNmYzYTYtMmI2MC00ZTdkLWJiMWItYjEzN2E3NTM3ZTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDE0MTM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMGEwNzQ2OTRkMjU4MTc0YmZiZjcwYWY4ODllMjZlNTA4ODgwOGVlOWNkZDdhZDI2MjA5NGFiYzg2NzVhMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9eo6a50tLbNhdXULNv1tGiPS03-oDD7lTsJjSc9smhA">
> When I have the keyboard size attached, it still doesn't work

Why `PanelType.keyboard` is used in `otherPanelWidget` callback?

**Comment by Danilz-2706** [comment]
I have updated this code. Performance is greatly improved with height.
<img width="491" alt="Screenshot 2024-07-25 at 11 49 29 PM" src="https://github.com/user-attachments/assets/9f64a65d-4b93-4df1-ae88-69fad62f662c">

**Comment by LinXunFeng** [comment]
Please update to version `0.2.0`.
