### ISSUE TITLE
记录键盘高度建议

### ISSUE THREAD

**Issue by Junesui** [LinXunFeng/flutter_chat_packages#6]
**panel_container.dart**　**247行**
修改为这样比较好

```
height = currentNativeKeyboardHeight == 0
              ? MediaQuery.viewInsetsOf(context).bottom -  MediaQuery.paddingOf(context).bottom
              : currentNativeKeyboardHeight;
```

![image](https://github.com/user-attachments/assets/423ee06f-831e-4d7b-a70e-62e4af6b1b84)

**Comment by Junesui** [comment]
补充一下，页面不用ＳａｆｅＡｒｅａ包裹的话上述问题不存在。但是底部面板也会和底部导航栏混在一起。（有些手机底部返回键，ｈｏｍｅ键在屏幕上）

另外changeKeyboardPanelHeight好像也可以解决，源码不改好像也ＯＫ。

没问题的话作者可以Ｃｌｏｓｅ。　打扰

**Comment by LinXunFeng** [comment]
感谢反馈，不过不同的开发者，使用的布局不同，该库尽量只处理常规情况，提供的 `safeAreaBottom` 和 `changeKeyboardPanelHeight` 就是为了给大家处理这种非常规的情况。
