### ISSUE TITLE
长按输入框，键盘弹起，但是输入框没有弹起

### ISSUE THREAD

**Issue by heipiu** [LinXunFeng/flutter_chat_packages#7]

**Comment by LinXunFeng** [comment]
复现步骤

**Comment by heipiu** [comment]
感谢大大开源，版本是 3.13.4 ，测试系统是Android，

Uploading 录屏2024-08-02 11.55.03.mov…

**Comment by heipiu** [comment]
感谢大大开源，flutter版本是 3.13.4 ，测试系统是Android

**Comment by heipiu** [comment]
Uploading 录屏2024-08-02 11.55.03.mov…

**Comment by heipiu** [comment]
https://github.com/user-attachments/assets/11062472-56ce-4ea3-8ab9-dcfdd5dd354f

**Comment by LinXunFeng** [comment]
示例自测不会，你可以跑示例看看。

还有你这个正常点击输入框，键盘有没有弹出来？

**Comment by heipiu** [comment]
解决了，解决了，谢谢大大，

**Comment by LinXunFeng** [comment]
觉得有帮助的话，给个 `Star` 吧

可以关注我们的公众号获取最新的通知

<img height="267.5" width="481.5" src="https://github.com/LinXunFeng/LinXunFeng/raw/master/static/img/FSAQR.png"/>
